# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ofac"
  s.version = "1.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kevin Tyll"]
  s.date = "2012-10-09"
  s.description = "Attempts to find a hit on the Office of Foreign Assets Control's Specially Designated Nationals list."
  s.email = "kevintyll@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "History.txt",
    "LICENSE",
    "PostInstall.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "generators/ofac_migration/.DS_Store",
    "generators/ofac_migration/ofac_migration_generator.rb",
    "generators/ofac_migration/templates/.DS_Store",
    "generators/ofac_migration/templates/migration.rb",
    "lib/generators/ofac_migration/build/build_generator.rb",
    "lib/generators/ofac_migration/build/templates/create_ofac_sdns.rb",
    "lib/ofac.rb",
    "lib/ofac/models/ofac.rb",
    "lib/ofac/models/ofac_sdn.rb",
    "lib/ofac/models/ofac_sdn_loader.rb",
    "lib/ofac/ofac_match.rb",
    "lib/ofac/ruby_string_extensions.rb",
    "lib/tasks/ofac.rake",
    "nbproject/project.properties",
    "nbproject/project.xml",
    "ofac.gemspec",
    "rdoc/CreateOfacSdns.html",
    "rdoc/Ofac.html",
    "rdoc/OfacMatch.html",
    "rdoc/OfacMigration.html",
    "rdoc/OfacMigration/Generators.html",
    "rdoc/OfacMigration/Generators/BuildGenerator.html",
    "rdoc/OfacSdn.html",
    "rdoc/OfacSdnLoader.html",
    "rdoc/README_rdoc.html",
    "rdoc/String.html",
    "rdoc/classes/Ofac.html",
    "rdoc/classes/OfacMatch.html",
    "rdoc/classes/OfacSdn.html",
    "rdoc/classes/OfacSdnLoader.html",
    "rdoc/classes/String.html",
    "rdoc/created.rid",
    "rdoc/files/README_rdoc.html",
    "rdoc/files/lib/ofac/models/ofac_rb.html",
    "rdoc/files/lib/ofac/models/ofac_sdn_loader_rb.html",
    "rdoc/files/lib/ofac/models/ofac_sdn_rb.html",
    "rdoc/files/lib/ofac/ofac_match_rb.html",
    "rdoc/files/lib/ofac/ruby_string_extensions_rb.html",
    "rdoc/files/lib/ofac_rb.html",
    "rdoc/fr_class_index.html",
    "rdoc/fr_file_index.html",
    "rdoc/fr_method_index.html",
    "rdoc/images/add.png",
    "rdoc/images/brick.png",
    "rdoc/images/brick_link.png",
    "rdoc/images/bug.png",
    "rdoc/images/bullet_black.png",
    "rdoc/images/bullet_toggle_minus.png",
    "rdoc/images/bullet_toggle_plus.png",
    "rdoc/images/date.png",
    "rdoc/images/delete.png",
    "rdoc/images/find.png",
    "rdoc/images/loadingAnimation.gif",
    "rdoc/images/macFFBgHack.png",
    "rdoc/images/package.png",
    "rdoc/images/page_green.png",
    "rdoc/images/page_white_text.png",
    "rdoc/images/page_white_width.png",
    "rdoc/images/plugin.png",
    "rdoc/images/ruby.png",
    "rdoc/images/tag_blue.png",
    "rdoc/images/tag_green.png",
    "rdoc/images/transparent.png",
    "rdoc/images/wrench.png",
    "rdoc/images/wrench_orange.png",
    "rdoc/images/zoom.png",
    "rdoc/index.html",
    "rdoc/js/darkfish.js",
    "rdoc/js/jquery.js",
    "rdoc/js/navigation.js",
    "rdoc/js/search.js",
    "rdoc/js/search_index.js",
    "rdoc/js/searcher.js",
    "rdoc/lib/generators/ofac_migration/build/build_generator_rb.html",
    "rdoc/lib/generators/ofac_migration/build/templates/create_ofac_sdns_rb.html",
    "rdoc/lib/ofac/models/ofac_rb.html",
    "rdoc/lib/ofac/models/ofac_sdn_loader_rb.html",
    "rdoc/lib/ofac/models/ofac_sdn_rb.html",
    "rdoc/lib/ofac/ofac_match_rb.html",
    "rdoc/lib/ofac/ruby_string_extensions_rb.html",
    "rdoc/lib/ofac_rb.html",
    "rdoc/rdoc-style.css",
    "rdoc/rdoc.css",
    "rdoc/table_of_contents.html",
    "test/files/test_address_data_load.pip",
    "test/files/test_alt_data_load.pip",
    "test/files/test_sdn_data_load.pip",
    "test/files/valid_flattened_file.csv",
    "test/mocks/test/ofac_sdn_loader.rb",
    "test/ofac_sdn_loader_test.rb",
    "test/ofac_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/kevintyll/ofac"
  s.post_install_message = "For more information on ofac, see http://kevintyll.github.com/ofac/\n\n* To create the necessary db migration, from the command line, run:\n    script/generate ofac_migration\n* Require the gem in your environment.rb file in the Rails::Initializer block:\n    config.gem 'kevintyll-ofac', :lib => 'ofac'\n* To load your table with the current OFAC data, from the command line, run:\n    rake ofac:update_data\n\n    * The OFAC data is not updated with any regularity, but you can sign up for email notifications when the data changes at\n        http://www.treas.gov/offices/enforcement/ofac/sdn/index.shtml."
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Attempts to find a hit on the Office of Foreign Assets Control's Specially Designated Nationals list."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

